"""
Waypoint 6: The 81-Lens and the Synthesis of 83
=================================================
Carmichael 449065 = 5 × 19 × 29 × 163
163-1 = 162 = 2 × 3^4 → C_81 Sylow subgroup!

The 81-lens is the VERTICAL complement to the 83-lens canopy.
81 = 3^4 is the deep core; 83 = next_prime(81) is its shadow.

Key results:
  - 1/81 ≈ 0.0123457 and 1/83 ≈ 0.0120482 — nearly identical
  - The 83-lens is the CANOPY SHADOW of the 81-lens core
  - 3^n depth casts shadow at next_prime(3^n)
  - The entire lens tree is generated by 3^n → shadow
"""

import numpy as np
from math import gcd
import json
import os

# ============================================================================
# CORE FUNCTIONS
# ============================================================================

def is_prime(n):
    if n < 2: return False
    for d in range(2, int(n**0.5) + 1):
        if n % d == 0: return False
    return True

def next_prime(n):
    candidate = n + 1
    while not is_prime(candidate):
        candidate += 1
    return candidate

def factorize(n):
    factors = {}
    temp = n
    d = 2
    while d * d <= temp:
        while temp % d == 0:
            factors[d] = factors.get(d, 0) + 1
            temp //= d
        d += 1 if d == 2 else 2
    if temp > 1:
        factors[temp] = factors.get(temp, 0) + 1
    return factors

# ============================================================================
# THE 81-LENS CARMICHAEL NUMBER
# ============================================================================

CARMICHAEL = 449065
FACTORS = [5, 19, 29, 163]
WAYPOINT = "wp6_81lens_synthesis"

print("=" * 72)
print("  WAYPOINT 6: THE 81-LENS AND THE SYNTHESIS OF 83")
print("=" * 72)
print()
print(f"Carmichael {CARMICHAEL} = {' × '.join(str(p) for p in FACTORS)}")
print()
print("Factor analysis:")
for p in FACTORS:
    pm1 = p - 1
    facts = factorize(pm1)
    fact_str = " × ".join(f"{q}^{e}" if e > 1 else str(q) for q, e in sorted(facts.items()))
    v3 = facts.get(3, 0)
    v2 = facts.get(2, 0)
    print(f"  p={p:3d}: p-1 = {pm1:3d} = {fact_str}")
    print(f"       2-Sylow: C_{2**v2}, 3-depth: {v3} (3^{v3} = {3**v3})")

print()

# ============================================================================
# THE 3-LENS DEPTH STRUCTURE
# ============================================================================

print("=" * 72)
print("  THE 3-LENS DEPTH STRUCTURE")
print("=" * 72)
print()

contributions = []
for p in FACTORS:
    pm1 = p - 1
    v3 = 0
    temp = pm1
    while temp % 3 == 0:
        v3 += 1
        temp //= 3
    if v3 > 0:
        contributions.append((p, v3))
        print(f"  p={p}: 3^{v3} = {3**v3} in p-1 → C_{3**v3} Sylow")

print()
print("Combined 3-Sylow: ", end="")
three_orders = [3**v for _, v in contributions]
print(" × ".join(f"C_{o}" for o in three_orders))
three_order_total = np.prod(three_orders)
three_exponent = max(three_orders)
print(f"  Order: {three_order_total}")
print(f"  Exponent: {three_exponent}")
print()

# Depth ladder
print("Depth ladder for the 3-lens:")
for i in range(1, 5):
    depth = 3**i
    coupling = 1.0 / depth
    exists = any(v >= i for _, v in contributions)
    marker = "★" if exists else " "
    print(f"  {marker} Level {i}: 1/{depth:<4} ≈ {coupling:.6f}  "
          f"(C_{depth} {'exists' if exists else 'not present'})")

print()

# ============================================================================
# COMPARISON OF 1/81 AND 1/83
# ============================================================================

print("=" * 72)
print("  THE SHADOW PRINCIPLE: 1/81 ≈ 1/83")
print("=" * 72)
print()

one_over_81 = 1.0 / 81.0
one_over_83 = 1.0 / 83.0
difference = abs(one_over_81 - one_over_83)
ratio = one_over_81 / one_over_83

print(f"1/81 = {one_over_81:.10f}")
print(f"1/83 = {one_over_83:.10f}")
print(f"Difference: {difference:.10f} = 2/(81×83) = 2/6723")
print(f"Ratio: {ratio:.10f}")
print()

print("The 83-lens coupling (1/83) is ALMOST IDENTICAL to")
print("the deepest 3-lens coupling (1/81).")
print()
print("83 = next_prime(81) = next_prime(3^4)")
print("The 83-lens IS the canopy shadow of the 81-lens core.")
print()

# ============================================================================
# THE COMPLETE SHADOW PATTERN
# ============================================================================

print("=" * 72)
print("  THE 3^n SHADOW GENERATES THE LENS TREE")
print("=" * 72)
print()

shadow_table = []
for n in range(1, 7):
    power = 3**n
    shadow = next_prime(power)
    next_after = next_prime(shadow)  # the next canopy prime
    one_over_power = 1.0 / power if n <= 4 else None  # only deep cores up to 3^4
    one_over_shadow = 1.0 / shadow
    
    shadow_table.append({
        'n': n,
        '3^n': power,
        'shadow': shadow,
        '1/3^n': one_over_power,
        '1/shadow': one_over_shadow
    })

print(f"{'n':>3} {'3^n':>10} {'Shadow':>8} {'1/3^n':>12} {'1/shadow':>12} {'Match?'}")
print("-" * 55)

for d in shadow_table:
    power_str = f"{d['1/3^n']:.6f}" if d['1/3^n'] else "—"
    shadow_str = f"{d['1/shadow']:.6f}"
    match = "✓" if d['1/3^n'] and abs(d['1/3^n'] - d['1/shadow']) < 0.1 else ""
    print(f"{d['n']:>3} {d['3^n']:>10} {d['shadow']:>8} {power_str:>12} {shadow_str:>12} {match:>6}")

print()
print("""
The pattern is clear:
  n=1: 1/3 vs 1/5 — rough match (same order of magnitude)
  n=2: 1/9 vs 1/11 — closer
  n=3: 1/27 vs 1/29 — very close
  n=4: 1/81 vs 1/83 — almost identical!
  
As n grows, the shadow coupling converges to the core coupling.
The canopy IS the shadow of the deep core.
""")

# ============================================================================
# TWO PATHS TO 83
# ============================================================================

print("=" * 72)
print("  TWO PATHS TO 83")
print("=" * 72)
print()
print("Path 1 (TOP-DOWN, Sophie Germain):")
print("  41 → 83 → 167")
print("  83 discovered through Carmichael numbers, Propus-668")
print()
print("Path 2 (BOTTOM-UP, 3^n shadow):")
print("  3 → 9 → 27 → 81 → shadow at 83")
print("  83 synthesized from the 81-lens core")
print()
print("The two paths MEET at 83.")
print("83 is simultaneously:")
print("  - A Sophie Germain prime (child of 41, parent of 167)")
print("  - The shadow of 3^4 = 81")
print()
print("This dual nature is why 83 produces the richest Propus structure.")
print()

# ============================================================================
# SYNTHESIS CARRIERS
# ============================================================================

print("=" * 72)
print("  THE SYNTHESIS TRIPLE")
print("=" * 72)
print()
print("Carriers that embody both paths:")
print("  163: 81-lens core (162 = 2 × 3^4)")
print("  19:  9-lens amplifier (18 = 2 × 3^2)")
print("  499: 83-canopy bridge (498 = 2 × 3 × 83)")
print()
print("These three carriers share the 3-lens at different depths.")
print("Together they span the full vertical + horizontal structure.")
print()

# ============================================================================
# SAVE
# ============================================================================

os.makedirs(f"{WAYPOINT}/output", exist_ok=True)

output = {
    'carmichael_81lens': CARMICHAEL,
    'factors': FACTORS,
    'three_sylow': {
        'contributions': [(p, v) for p, v in contributions],
        'orders': [int(o) for o in three_orders],
        'total_order': int(three_order_total),
        'exponent': int(three_exponent)
    },
    'coupling_comparison': {
        '1/81': one_over_81,
        '1/83': one_over_83,
        'difference': difference,
        'ratio': ratio
    },
    'shadow_table': shadow_table,
    'two_paths_to_83': [
        'Top-down: 41 → 83 → 167 (SG chain)',
        'Bottom-up: 3 → 9 → 27 → 81 → 83 (3^n shadow)'
    ]
}

with open(f'{WAYPOINT}/output/81lens_synthesis.json', 'w') as f:
    json.dump(output, f, indent=2)

print(f"Saved: {WAYPOINT}/output/81lens_synthesis.json")
print()
print("=" * 72)
print("  WAYPOINT 6 COMPLETE — 81-LENS SYNTHESIS")
print("=" * 72)
